// PostgreSQL database helper.
//
// This module contains reusable functions for database validation
// and test data cleanup in Playwright tests.
//
// Database configuration is read from environment variables.
// Credentials are not stored directly in the source code.

const { Client } = require("pg");


// ============================================================
// Database Client
// ============================================================

// Create and return a PostgreSQL client.
//
// Connection settings are loaded from environment variables
// defined in the local .env file.
function createClient() {

  return new Client({
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    database: process.env.DB_DATABASE,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD
  });

}


// ============================================================
// Check Message
// ============================================================

// Check whether a contact message exists in the database.
//
// The function searches by both email and message because our
// Playwright test generates unique values for every execution.
//
// Using parameterized values ($1 and $2) avoids constructing
// SQL queries by concatenating test data directly into SQL.
async function messageExists(email, message) {

  const client = createClient();

  try {

    // Open the database connection.
    await client.connect();


    // Search for the exact message created by the test.
    const result = await client.query(
      `
        SELECT id
        FROM messages
        WHERE email = $1
          AND message = $2
        LIMIT 1
      `,
      [email, message]
    );


    // If at least one row was returned,
    // the message exists in PostgreSQL.
    return result.rowCount > 0;

  } finally {

    // Always close the database connection,
    // even if the query fails.
    await client.end();

  }

}


// ============================================================
// Delete Message
// ============================================================

// Delete a contact message created by an automated test.
//
// Automated tests should clean up the test data they create
// so repeated test executions do not fill the database
// with unnecessary test records.
//
// The same unique email and message used during validation
// are also used to identify the exact record for deletion.
async function deleteMessage(email, message) {

  const client = createClient();

  try {

    // Open the database connection.
    await client.connect();


    // Delete only the record matching both the unique
    // email and message generated by the current test.
    //
    // Parameterized values protect the query from SQL injection
    // and avoid inserting test data directly into the SQL string.
    const result = await client.query(
      `
        DELETE FROM messages
        WHERE email = $1
          AND message = $2
      `,
      [email, message]
    );


    // Return the number of deleted rows.
    //
    // Normally this should be 1 because the test data
    // is unique for every execution.
    return result.rowCount;

  } finally {

    // Always close the database connection.
    await client.end();

  }

}


// ============================================================
// Exports
// ============================================================

// Export reusable database helper functions so they can
// be imported and used inside Playwright tests.
module.exports = {
  messageExists,
  deleteMessage
};